### ISSUE TITLE
Edge/Firefox Issues

### ISSUE THREAD

**Issue by Paladinleeds** [ClubWumpus/Flappy-Wumpus#11]
Game doesn't load on Microsoft Edge or Mozilla Firefox on Windows 10 Pro. Have not yet tested Chrome mobile, Firefox mobile, and Edge mobile. The loading bar gets stuck at around 80%...  

EDIT: Testing in mobile browsers.
Edge: Not working
Chrome: Works, but scaling looks off. Game needs resizing.
Firefox: Not tested

**Comment by ghost** [comment]
@Paladinleeds Generic should be looking into it now. :)

**Comment by AGenericGamer** [comment]
As @Stoupedog pointed out, the issue seems to be with WebAudio, even though firefox is supposed to support it.
![image](https://cloud.githubusercontent.com/assets/22906278/19669996/805fc448-99ff-11e6-8c94-6cbb2f2932ad.png)

**Comment by AGenericGamer** [comment]
Thee issue might lie within enchant.js, I'll have to look into it more later this week.

**Comment by ghost** [comment]
Issue has been resolved and fixed!
