### ISSUE TITLE
Sounds

### ISSUE THREAD

**Issue by AGenericGamer** [ClubWumpus/Flappy-Wumpus#40]
For the love of god we need to figure out how enchant.js uses sounds so we can use all the assets in our sounds folder (flap, score, death, ect.)

**Comment by Stoupedog** [comment]
Apparently using sounds through enchant.js can be pretty buggy (I tried and failed).
As game.js is still a javascript file, this kinda format seems to work:
`var gameOverSound = new Audio('sounds/game-over.mp3');`
`gameOverSound.play();`

Added flap and game over sounds in https://github.com/ClubWumpus/Flappy-Wumpus/commit/5648de4defd8b238b317a4d357b66e599d35d4dd
