### ISSUE TITLE
Blurple vigenette

### ISSUE THREAD

**Issue by AGenericGamer** [ClubWumpus/Flappy-Wumpus#41]
![image](https://cloud.githubusercontent.com/assets/22906278/19678662/5cb09d84-9a3a-11e6-832b-e668eca0a7fd.png)
It looks kinda cool. We can mess with the alpha on it if we need too, and we could have it change colors in party mode.

**Comment by AGenericGamer** [comment]
Okay so, after spending 4+ hours on trying to get this to work, I've exhausted every single resource I could find on trying to do this in css. Let's look into trying to build it into the game itself.

**Comment by ghost** [comment]
Scrapped it.
