### ISSUE TITLE
Game Over Menu

### ISSUE THREAD

**Issue by franc-ist** [ClubWumpus/Flappy-Wumpus#88]
When you fail, a simple click causes the game to restart, however if you were really in the zone, you may not have seen your score. 
#### Suggestions:
- Make a button that says "restart"
- Add a leaderboard

**Comment by AGenericGamer** [comment]
This is similar to #36, but I'll keep it :+1:

**Comment by Shuu37** [comment]
Let's merge this with #36 @AGenericGamer

**Comment by AGenericGamer** [comment]
Merging with #36

**Comment by AGenericGamer** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add game over options](https://trello.com/c/qlNEMdr0/9-add-game-over-options)
